function [cmd] = create_model_spawn_command(sub_folder, name_number, collor,scale)
n = 10; %new line character, linux:10  win:[10 13]
path = strcat(fileparts(which('create_model_spawn_command.m')),'/',sub_folder);

file_name = ['test_poly_' num2str(name_number) '.stl'];
offset_file_name = ['test_poly_' num2str(name_number) '.txt'];
f = fopen(strcat(sub_folder,offset_file_name));
offset = fscanf(f,'%f');
    cmd = ['rosservice call /gazebo/spawn_sdf_model "model_name: ''model_' num2str(name_number) '''' n...
'model_xml: ''<sdf version="1.4"> <model name="model_' num2str(name_number) '"> <pose>' num2str(offset') ' 0 0 0</pose> <allow_auto_disable>false</allow_auto_disable> <link name="link"> <visual name="visual"> <geometry> <mesh><uri>' path file_name '</uri><scale>' num2str(scale) ' ' num2str(scale) ' ' num2str(scale) '</scale></mesh> </geometry> <material> <ambient> ' num2str(collor) ' 1</ambient> <diffuse> ' num2str(collor) ' 1</diffuse> <specular>0 1 0 1</specular> <emissive>0 0 0 0</emissive> </material> </visual> </link> <static>1</static> </model> </sdf>''' n...
'robot_namespace: ''dummy''' n...
'initial_pose:' n...
' position: {x: ' num2str(offset(1)) ', y: ' num2str(offset(2)) ', z: ' num2str(offset(3)) '}' n...
' orientation: {x: 0.0, y: 0.0, z: 0.0, w: 0.0}' n...
'reference_frame: ''world''"'];
end