function create_world_file(sub_folder)
%afficheur de limites
files = dir(strcat(sub_folder,'*.stl'));
offset_files = dir(strcat(sub_folder,'*.txt'));
path = strcat(fileparts(which('create_world_file.m')),'/',sub_folder);
n=length(files);
cmap = hsv(n);

n = 10; %new line character, linux:10  win:[10 13]
f = fopen('matlab_gazebo_world_file.world','w'); %open dae file for writing
t = datestr(now+java.util.Date().getTimezoneOffset()/24/60,'yyyy-mm-ddTHH:MM:SSZ'); %utc time stamp
wr = @(x)fwrite(f,x,'char'); %function to write text to file
wr(['<sdf version="1.4">' n...                                    
    '  <world name="default">' n...                               
    '    <!-- include sun and ground plane -->' n...              
    '    <include><uri>model://sun</uri></include>' n...          
    '    <include><uri>model://ground_plane</uri></include>' n]);  

for i=1:numel(files)
    file_name = files(i).name;
    offset = fileread(strcat(sub_folder,offset_files(i).name));
wr(['<model name="' file_name(1:end-4) '">' n...
    '      <pose>' offset ' 0 0 0</pose>' n...
    '      <allow_auto_disable>false</allow_auto_disable>' n...
    '      <link name="link">' n...
    '        <visual name="visual">' n...
    '          <geometry>' n...
    '            <mesh><uri>' path file_name '</uri><scale>0.001 0.001 0.001</scale></mesh>' n...
    '          </geometry>' n...
    '          <material>' n...
    '            <ambient>' num2str(cmap(i,:)) ' 0.7</ambient>' n...
    '            <diffuse>' num2str(cmap(i,:)) ' 0.7</diffuse>' n...
    '            <specular>0.1 0.1 0.1 0.7</specular>' n...
    '            <emissive>0 0 0 0</emissive>' n...
    '          </material>' n...
    '        </visual>' n...
    '      </link>' n...
    '      <static>1</static>' n...
    '    </model>' n]);
end
wr(['<light name=''user_spot_light_0'' type=''spot''>' n...
    '  <pose frame=''''>-0.5 -2.1 3 0 -0 0</pose>' n...
    '  <diffuse>0.5 0.5 0.5 1</diffuse>' n...
    '  <specular>0.1 0.1 0.1 1</specular>' n...
    '  <direction>0 0 -1</direction>' n...
    '  <attenuation>' n...
    '    <range>20</range>' n...
    '    <constant>0.5</constant>' n...
    '    <linear>0.01</linear>' n...
    '    <quadratic>0.001</quadratic>' n...
    '  </attenuation>' n...
    '  <cast_shadows>0</cast_shadows>' n...
    '  <spot>' n...
    '    <inner_angle>0.6</inner_angle>' n...
    '    <outer_angle>1</outer_angle>' n...
    '    <falloff>1</falloff>' n...
    '  </spot>' n...
    '</light>' n...
    '<light name=''user_spot_light_0_clone'' type=''spot''>' n...
    '  <pose frame=''''>-0.751145 1.62768 3 0 -0 0</pose>' n...
    '  <diffuse>0.498039 0.498039 0.498039 1</diffuse>' n...
    '  <specular>0.0980392 0.0980392 0.0980392 1</specular>' n...
    '  <direction>0 0 -1</direction>' n...
    '  <attenuation>' n...
    '    <range>20</range>' n...
    '    <constant>0.3</constant>' n...
    '    <linear>0</linear>' n...
    '    <quadratic>0.001</quadratic>' n...
    '  </attenuation>' n...
    '  <cast_shadows>1</cast_shadows>' n...
    '  <spot>' n...
    '    <inner_angle>1</inner_angle>' n...
    '    <outer_angle>2</outer_angle>' n...
    '    <falloff>0.5</falloff>' n...
    '  </spot>' n...
    '</light>' n...
    '    <gui fullscreen="0">' n...
    '      <camera name="user_camera">' n...
    '        <pose>-1.5 -1.5 2.2  0.0 0.4 0.707</pose>' n...
    '        <view_controller>orbit</view_controller>' n...
    '      </camera>' n...
    '    </gui>' n...
    '  </world>' n...
    '</sdf>' n]);
fclose(f); %close file



