function create_world_file(sub_folder)
%afficheur de limites
files = dir(strcat(sub_folder,'*.stl'));
path = strcat(fileparts(which('create_world_file.m')),'/',sub_folder);
n=length(files);
cmap = hsv(n);

n = 10; %new line character, linux:10  win:[10 13]
f = fopen('matlab_gazebo_world_file.world','w'); %open dae file for writing
t = datestr(now+java.util.Date().getTimezoneOffset()/24/60,'yyyy-mm-ddTHH:MM:SSZ'); %utc time stamp
wr = @(x)fwrite(f,x,'char'); %function to write text to file
wr(['<sdf version="1.4">' n...                                    
    '  <world name="default">' n...                               
    '    <!-- include sun and ground plane -->' n...              
    '    <include><uri>model://sun</uri></include>' n...          
    '    <include><uri>model://ground_plane</uri></include>' n]);  

for i=1:numel(files)
    file_name = files(i).name;
wr(['<model name="' file_name(1:end-4) '">' n...
    '      <pose>0.0 0 0.815 0 0 0</pose>' n...
    '      <allow_auto_disable>false</allow_auto_disable>' n...
    '      <link name="link">' n...
    '        <visual name="visual">' n...
    '          <geometry>' n...
    '            <mesh><uri>' path file_name '</uri><scale>0.001 0.001 0.001</scale></mesh>' n...
    '          </geometry>' n...
    '          <material>' n...
    '            <ambient>' num2str(cmap(i,:)) ' 1</ambient>' n...
    '            <diffuse>' num2str(cmap(i,:)) ' 1</diffuse>' n...
    '            <specular>0.1 0.1 0.1 1</specular>' n...
    '            <emissive>0 0 0 0</emissive>' n...
    '          </material>' n...
    '        </visual>' n...
    '      </link>' n...
    '      <static>1</static>' n...
    '    </model>' n]);
end
wr(['    <gui fullscreen="0">' n...
    '      <camera name="user_camera">' n...
    '        <pose>6.5 0.0 1.5  0.0 0.0 -3.14159</pose>' n...
    '        <view_controller>orbit</view_controller>' n...
    '      </camera>' n...
    '    </gui>' n...
    '  </world>' n...
    '</sdf>' n]);
fclose(f); %close file



